import { Router } from 'express';
import authRoutes from './auth.routes';
import courseRoutes from './course.routes';
import assignmentRoutes from './assignment.routes';
import quizRoutes from './quiz.routes';
import resultRoutes from './result.routes';
import paymentRoutes from './payment.routes';
import hostelRoutes from './hostel.routes';
import userRoutes from './user.routes';
import notificationRoutes from './notification.routes';
import dashboardRoutes from './dashboard.routes';
import messageRoutes from './message.routes';
import attendanceRoutes from './attendance.routes';
import scholarshipRoutes from './scholarship.routes';
import clearanceRoutes from './clearance.routes';
import appealRoutes from './appeal.routes';
import studentRoutes from './student.routes';
import lecturerRoutes from './lecturer.routes';
import hodRoutes from './hod.routes';
import bursaryRoutes from './bursary.routes';
import adminRoutes from './admin.routes';
import settingsRoutes from './settings.routes';
import fileRoutes from './file.routes';
import webhookRoutes from './webhook.routes';

const router = Router();

router.use('/auth', authRoutes);
router.use('/courses', courseRoutes);
router.use('/assignments', assignmentRoutes);
router.use('/quizzes', quizRoutes);
router.use('/results', resultRoutes);
router.use('/payments', paymentRoutes);
router.use('/hostels', hostelRoutes);
router.use('/users', userRoutes);
router.use('/notifications', notificationRoutes);
router.use('/messages', messageRoutes);
router.use('/', attendanceRoutes);
router.use('/', scholarshipRoutes);
router.use('/', clearanceRoutes);
router.use('/', appealRoutes);
router.use('/', studentRoutes);
router.use('/lecturers', lecturerRoutes);
router.use('/hod', hodRoutes);
router.use('/bursary', bursaryRoutes);
router.use('/admin', adminRoutes);
router.use('/', settingsRoutes);
router.use('/', fileRoutes);
router.use('/', dashboardRoutes);
router.use('/', webhookRoutes);

export default router;
